package online.rollnexa.api;
import jakarta.servlet.http.*; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import online.rollnexa.api.Dto.*; import online.rollnexa.domain.User; import online.rollnexa.repository.UserRepository; import online.rollnexa.service.*; import org.springframework.http.*; import org.springframework.security.authentication.*; import org.springframework.security.core.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.context.HttpSessionSecurityContextRepository; import org.springframework.web.bind.annotation.*; import java.util.Map;
@RestController @RequestMapping("/api/auth") @RequiredArgsConstructor
public class AuthController {
 private final UserRepository users; private final PasswordEncoder encoder; private final AuthenticationManager authenticationManager; private final ViewMapper mapper;
 @GetMapping("/csrf") public Map<String,String> csrf(org.springframework.security.web.csrf.CsrfToken token){return Map.of("token",token.getToken());}
 @PostMapping("/register") public ResponseEntity<AuthResponse> register(@Valid @RequestBody RegisterRequest in,HttpServletRequest req){if(users.existsByUsernameIgnoreCase(in.username()))throw new ApiException(HttpStatus.CONFLICT,"USERNAME_TAKEN","El nombre de usuario ya está en uso");if(users.existsByEmailIgnoreCase(in.email()))throw new ApiException(HttpStatus.CONFLICT,"EMAIL_TAKEN","El email ya está registrado");var u=new User();u.setUsername(in.username().trim());u.setEmail(in.email().trim().toLowerCase());u.setPasswordHash(encoder.encode(in.password()));users.save(u);return ResponseEntity.status(201).body(loginInternal(u.getUsername(),in.password(),req));}
 @PostMapping("/login") public AuthResponse login(@Valid @RequestBody LoginRequest in,HttpServletRequest req){return loginInternal(in.username(),in.password(),req);}
 private AuthResponse loginInternal(String username,String password,HttpServletRequest req){Authentication auth;try{auth=authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(username,password));}catch(AuthenticationException e){throw new ApiException(HttpStatus.UNAUTHORIZED,"BAD_CREDENTIALS","Usuario o contraseña incorrectos");}var context=SecurityContextHolder.createEmptyContext();context.setAuthentication(auth);SecurityContextHolder.setContext(context);req.getSession(true).setAttribute(HttpSessionSecurityContextRepository.SPRING_SECURITY_CONTEXT_KEY,context);var u=users.findByUsernameIgnoreCase(auth.getName()).orElseThrow();return new AuthResponse(true,mapper.user(u));}
 @GetMapping("/me") public AuthResponse me(Authentication auth){if(auth==null||!auth.isAuthenticated()||"anonymousUser".equals(auth.getPrincipal()))return new AuthResponse(false,null);var u=users.findByUsernameIgnoreCase(auth.getName()).orElse(null);return new AuthResponse(u!=null,u==null?null:mapper.user(u));}
}

