package online.rollnexa.service;
import lombok.RequiredArgsConstructor; import online.rollnexa.api.*; import online.rollnexa.api.Dto.*; import online.rollnexa.domain.*; import online.rollnexa.repository.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant; import java.util.*;
@Service @RequiredArgsConstructor public class FriendService {
 private final FriendshipRepository repo; private final UserRepository users; private final ViewMapper mapper;
 @Transactional public FriendshipView request(User from,String username){var to=users.findByUsernameIgnoreCase(username).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"USER_NOT_FOUND","El usuario no existe"));if(from.getId().equals(to.getId()))throw new ApiException(HttpStatus.BAD_REQUEST,"SELF_FRIEND","No podés agregarte a vos mismo");if(repo.between(from.getId(),to.getId()).isPresent())throw new ApiException(HttpStatus.CONFLICT,"FRIENDSHIP_EXISTS","Ya existe una solicitud o amistad");var f=new Friendship();f.setRequester(from);f.setAddressee(to);repo.save(f);return view(f,from.getId());}
 @Transactional public FriendshipView resolve(User user,Long id,boolean accept){var f=repo.findById(id).filter(x->x.getAddressee().getId().equals(user.getId())&&x.getStatus()==Friendship.Status.PENDING).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"FRIEND_REQUEST_NOT_FOUND","La solicitud no existe"));f.setStatus(accept?Friendship.Status.ACCEPTED:Friendship.Status.REJECTED);return view(f,user.getId());}
 @Transactional(readOnly=true) public List<FriendshipView> list(User user){var all=new ArrayList<>(repo.acceptedFor(user.getId()));all.addAll(repo.findByAddresseeIdAndStatus(user.getId(),Friendship.Status.PENDING));return all.stream().map(f->view(f,user.getId())).toList();}
 private FriendshipView view(Friendship f,Long me){var other=f.getRequester().getId().equals(me)?f.getAddressee():f.getRequester();boolean online=other.getLastSeenAt()!=null&&other.getLastSeenAt().isAfter(Instant.now().minusSeconds(120));return new FriendshipView(f.getId(),mapper.user(other),f.getStatus(),f.getAddressee().getId().equals(me),online);}
}
