package online.rollnexa.service;
import lombok.RequiredArgsConstructor; import online.rollnexa.api.*; import online.rollnexa.api.Dto.*; import online.rollnexa.domain.*; import online.rollnexa.repository.*; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant; import java.util.*;
@Service @RequiredArgsConstructor
public class RoomService {
 private final RoomRepository rooms; private final RoomMemberRepository members; private final JoinRequestRepository requests; private final ViewMapper mapper;
 @Transactional(readOnly=true) public Page<RoomCard> search(String q,String tag,int page,int size,Long viewer){return rooms.search(clean(q),clean(tag),PageRequest.of(Math.max(0,page),Math.min(Math.max(size,1),24),Sort.by(Sort.Direction.DESC,"createdAt"))).map(r->mapper.room(r,viewer));}
 @Transactional public RoomCard create(RoomCreate in,User creator){var r=new Room();apply(r,in);rooms.save(r);var m=new RoomMember();m.setRoom(r);m.setUser(creator);m.setRole(RoomMember.Role.GM);members.save(m);return mapper.room(r,creator.getId());}
 @Transactional(readOnly=true) public RoomDetail detail(Long id,Long viewer){var r=get(id);var ms=members.findMembers(id);String role=viewer==null?null:ms.stream().filter(m->m.getUser().getId().equals(viewer)).map(m->m.getRole().name()).findFirst().orElse(null);return new RoomDetail(mapper.room(r,viewer),ms.stream().map(mapper::member).toList(),role);}
 @Transactional public RoomCard edit(Long id,RoomCreate in,User user){requireGm(id,user.getId());var r=get(id);apply(r,in);return mapper.room(r,user.getId());}
 @Transactional public JoinResult join(Long id,User user){var r=rooms.lockById(id).orElseThrow(()->notFound());if(members.existsByRoomIdAndUserId(id,user.getId()))throw conflict("ALREADY_MEMBER","Ya formás parte de esta sala");if(members.countByRoomId(id)>=r.getMaxParticipants())throw conflict("ROOM_FULL","La sala está completa");var previous=requests.findByRoomIdAndUserId(id,user.getId());if(r.getJoinMode()==Room.JoinMode.OPEN){previous.ifPresent(requests::delete);addPlayer(r,user);return new JoinResult("JOINED","Te uniste a la sala");}if(previous.isPresent()&&previous.get().getStatus()==JoinRequest.Status.PENDING)throw conflict("REQUEST_EXISTS","Ya enviaste una solicitud");var request=previous.orElseGet(JoinRequest::new);request.setRoom(r);request.setUser(user);request.setStatus(JoinRequest.Status.PENDING);request.setCreatedAt(Instant.now());request.setResolvedAt(null);requests.save(request);return new JoinResult("PENDING","Solicitud enviada al GM");}
 @Transactional(readOnly=true) public List<JoinRequestView> pending(Long roomId,User gm){requireGm(roomId,gm.getId());return requests.findByRoomIdAndStatusOrderByCreatedAtAsc(roomId,JoinRequest.Status.PENDING).stream().map(r->new JoinRequestView(r.getId(),mapper.user(r.getUser()),r.getCreatedAt())).toList();}
 @Transactional public void resolve(Long roomId,Long requestId,boolean accept,User gm){requireGm(roomId,gm.getId());var req=requests.findById(requestId).filter(x->x.getRoom().getId().equals(roomId)).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"REQUEST_NOT_FOUND","La solicitud no existe"));if(req.getStatus()!=JoinRequest.Status.PENDING)throw conflict("REQUEST_RESOLVED","La solicitud ya fue resuelta");if(accept){var room=rooms.lockById(roomId).orElseThrow(()->notFound());if(members.countByRoomId(roomId)>=room.getMaxParticipants())throw conflict("ROOM_FULL","La sala está completa");if(!members.existsByRoomIdAndUserId(roomId,req.getUser().getId()))addPlayer(room,req.getUser());req.setStatus(JoinRequest.Status.ACCEPTED);}else req.setStatus(JoinRequest.Status.REJECTED);req.setResolvedAt(Instant.now());}
 @Transactional public void leave(Long roomId,User user){var m=members.findByRoomIdAndUserId(roomId,user.getId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"MEMBERSHIP_NOT_FOUND","No pertenecés a la sala"));if(m.getRole()==RoomMember.Role.GM)throw new ApiException(HttpStatus.CONFLICT,"GM_CANNOT_LEAVE","El GM debe transferir o cerrar la sala");members.delete(m);}
 @Transactional public void kick(Long roomId,Long userId,User gm){requireGm(roomId,gm.getId());var m=members.findByRoomIdAndUserId(roomId,userId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"MEMBERSHIP_NOT_FOUND","El miembro no existe"));if(m.getRole()==RoomMember.Role.GM)throw conflict("CANNOT_KICK_GM","No se puede expulsar al GM");members.delete(m);}
 public RoomMember requireMember(Long roomId,Long userId){return members.findByRoomIdAndUserId(roomId,userId).orElseThrow(()->new ApiException(HttpStatus.FORBIDDEN,"MEMBERS_ONLY","Solo los miembros pueden realizar esta acción"));}
 public RoomMember requireGm(Long roomId,Long userId){var m=requireMember(roomId,userId);if(m.getRole()!=RoomMember.Role.GM)throw new ApiException(HttpStatus.FORBIDDEN,"GM_ONLY","Esta acción requiere permisos de GM");return m;}
 private void addPlayer(Room r,User u){var m=new RoomMember();m.setRoom(r);m.setUser(u);m.setRole(RoomMember.Role.PLAYER);members.save(m);}
 private Room get(Long id){return rooms.findById(id).orElseThrow(()->notFound());}
 private ApiException notFound(){return new ApiException(HttpStatus.NOT_FOUND,"ROOM_NOT_FOUND","La sala solicitada no existe");}
 private ApiException conflict(String code,String message){return new ApiException(HttpStatus.CONFLICT,code,message);}
 private String clean(String v){return v==null?"":v.trim();}
 private void apply(Room r,RoomCreate in){r.setName(in.name().trim());r.setDescription(in.description().trim());r.setGameSystem(in.gameSystem().trim());r.setCampaignType(in.campaignType());r.setMaxParticipants(in.maxParticipants());r.setTags(String.join(",",in.tags()==null?List.of():in.tags().stream().map(String::trim).filter(s->!s.isBlank()).distinct().toList()));r.setJoinMode(in.joinMode());}
}

