package online.rollnexa.service;
import lombok.RequiredArgsConstructor; import online.rollnexa.api.*; import online.rollnexa.api.Dto.*; import online.rollnexa.domain.*; import online.rollnexa.repository.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import java.util.stream.*;
@Service @RequiredArgsConstructor
public class ScheduleService {
 private final AvailabilityRepository availability; private final GameSessionRepository sessions; private final SessionResponseRepository responses; private final RoomRepository rooms; private final RoomMemberRepository members; private final RoomService roomService; private final ViewMapper mapper;
 @Transactional public AvailabilityView vote(Long roomId,User user,AvailabilityInput in){roomService.requireMember(roomId,user.getId());if(in.startTime()!=null&&in.endTime()!=null&&!in.endTime().isAfter(in.startTime()))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_TIME_RANGE","El horario de fin debe ser posterior al inicio");if(in.date().isBefore(LocalDate.now()))throw new ApiException(HttpStatus.BAD_REQUEST,"PAST_DATE","No se puede votar una fecha pasada");var a=availability.findByRoomIdAndUserIdAndDate(roomId,user.getId(),in.date()).orElseGet(Availability::new);a.setRoom(rooms.getReferenceById(roomId));a.setUser(user);a.setDate(in.date());a.setStartTime(in.startTime());a.setEndTime(in.endTime());a.setAvailable(in.available());availability.save(a);return view(a);}
 @Transactional(readOnly=true) public Map<String,Object> calendar(Long roomId,User user,LocalDate from,LocalDate to){roomService.requireMember(roomId,user.getId());if(to.isBefore(from)||to.isAfter(from.plusDays(62)))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_RANGE","El rango debe abarcar hasta 63 días");var list=availability.findByRoomIdAndDateBetweenOrderByDateAsc(roomId,from,to);long total=members.countByRoomId(roomId);var summary=list.stream().filter(Availability::isAvailable).collect(Collectors.groupingBy(Availability::getDate,TreeMap::new,Collectors.counting())).entrySet().stream().map(e->new AvailabilityDay(e.getKey(),e.getValue(),total)).toList();return Map.of("votes",list.stream().map(this::view).toList(),"summary",summary,"memberCount",total);}
 @Transactional public SessionView createSession(Long roomId,User gm,SessionInput in){roomService.requireGm(roomId,gm.getId());var s=new GameSession();s.setRoom(rooms.getReferenceById(roomId));s.setTitle(in.title().trim());s.setScheduledAt(in.scheduledAt());sessions.save(s);return sessionView(s,gm.getId());}
 @Transactional(readOnly=true) public List<SessionView> listSessions(Long roomId,User user){roomService.requireMember(roomId,user.getId());return sessions.findByRoomIdOrderByScheduledAtAsc(roomId).stream().map(s->sessionView(s,user.getId())).toList();}
 @Transactional public SessionView respond(Long roomId,Long sessionId,User user,boolean availableValue){roomService.requireMember(roomId,user.getId());var s=getSession(roomId,sessionId);var r=responses.findBySessionIdAndUserId(sessionId,user.getId()).orElseGet(SessionResponse::new);r.setSession(s);r.setUser(user);r.setAvailable(availableValue);responses.save(r);return sessionView(s,user.getId());}
 @Transactional public SessionView confirm(Long roomId,Long sessionId,User gm){roomService.requireGm(roomId,gm.getId());var s=getSession(roomId,sessionId);s.setStatus(GameSession.Status.CONFIRMED);return sessionView(s,gm.getId());}
 private GameSession getSession(Long roomId,Long id){return sessions.findById(id).filter(s->s.getRoom().getId().equals(roomId)).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"SESSION_NOT_FOUND","La sesión no existe"));}
 private AvailabilityView view(Availability a){return new AvailabilityView(a.getId(),a.getDate(),a.getStartTime(),a.getEndTime(),a.isAvailable(),mapper.user(a.getUser()));}
 private SessionView sessionView(GameSession s,Long userId){var rs=responses.findBySessionId(s.getId());Boolean mine=rs.stream().filter(r->r.getUser().getId().equals(userId)).map(SessionResponse::isAvailable).findFirst().orElse(null);return new SessionView(s.getId(),s.getTitle(),s.getScheduledAt(),s.getStatus(),rs.stream().filter(SessionResponse::isAvailable).count(),members.countByRoomId(s.getRoom().getId()),mine);}
}

