package online.rollnexa.service;
import jakarta.servlet.http.HttpSession; import lombok.RequiredArgsConstructor; import online.rollnexa.api.*; import online.rollnexa.api.Dto.*; import online.rollnexa.domain.*; import online.rollnexa.repository.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class UserService {
 private final UserRepository users; private final RoomMemberRepository members; private final FriendshipRepository friendships; private final ViewMapper mapper; private final LevelService levels;
 @Transactional(readOnly=true) public UserProfile profile(String username,Long viewerId){var u=users.findByUsernameIgnoreCase(username).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"USER_NOT_FOUND","El usuario no existe"));var ms=members.findByUserIdOrderByJoinedAtDesc(u.getId());boolean friend=viewerId!=null&&friendships.between(viewerId,u.getId()).filter(f->f.getStatus()==Friendship.Status.ACCEPTED).isPresent();return new UserProfile(u.getId(),u.getUsername(),u.getAvatarUrl(),u.getBio(),u.getLevel(),u.getExperience(),levels.xpForLevel(u.getLevel()),u.getActivityMinutes(),ms.stream().filter(m->!m.getRoom().isCompleted()).count(),ms.stream().filter(m->m.getRoom().isCompleted()).count(),friend);}
 @Transactional(readOnly=true) public List<RoomCard> myRooms(User user){return members.findByUserIdOrderByJoinedAtDesc(user.getId()).stream().map(m->mapper.room(m.getRoom(),user.getId())).toList();}
 @Transactional public UserSummary activity(User user,int claimed,HttpSession session){var now=Instant.now();var key="activity-last-award";var last=(Instant)session.getAttribute(key);if(last!=null&&Duration.between(last,now).getSeconds()<45)throw new ApiException(HttpStatus.TOO_MANY_REQUESTS,"ACTIVITY_THROTTLED","Esperá antes de registrar más actividad");int minutes=Math.min(15,Math.max(1,claimed));user.setActivityMinutes(user.getActivityMinutes()+minutes);user.setExperience(user.getExperience()+minutes*2L);user.setLevel(levels.levelFor(user.getExperience()));session.setAttribute(key,now);return mapper.user(user);}
 @Transactional public void presence(User user){user.setLastSeenAt(Instant.now());}
}
